baseurl      = "https://nickohristov.de"
title        = "Hi, I'm Nicko Hristov!"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
rssLimit     = 5
enableEmoji  = true

[author]
  name = "Nicko Hristov"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  timeZone	  = "Europe/Berlin"

  # Subtitle for home
  homeSubtitle = "<a rel=\"me\" href=\"https://mastodon.social/@nel0x\">Mastodon</a>A student by day, a coder by night."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  
  # Disable automatic generation of robots.txt from template
  enableRobotsTXT = false

  # Enable theme toggle
  enableThemeToggle = true

  # Metadata mostly used in document's head
  description = "Nicko's personal site"
  keywords = "homepage, blog"
  images = [""]

  # Primary Footer Menu
  [params.footer]
    trademark = true
    rss = true
    bottomText = ["<span class=\"text\"></span>"
#      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
#      "Made with &#10084; by <a href=\"https://github.com/rhazdon\">rhazdon</a>"
    ]
    
  [[params.social]]
    name = "email"
    url  = "http://gpg.nickohristov.de"

  [[params.social]]
    name = "matrix"
    url  = "https://matrix.to/#/@quick.silver:matrix.org"
    
  [[params.social]]
    name = "github"
    url  = "https://github.com/nel0x"
    
  [[params.social]]
    name = "monero"
    url  = "/donation"

  [params.logo]
    logoMark     = "$"
    logoText = "cd ~"
    logoHomeLink = "/"
    logoCursorColor =  "#379cff"
    logoCursorAnimate  = "1.1s"

[taxonomies]
    category = "categories"
    tag      = "tags"
    
[languages]
  [languages.en]
    subtitle = "A student by day, a coder by night."
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    name       = "Posts"
    url        = "/posts"
    weight     = 1

  [[menu.main]]
    name       = "About"
    url        = "/about"
    weight     = 2

  [[menu.main]]
    name       = "Sources"
    url        = "/sources"
    weight     = 3
